name: data_management
description: Collection of service with advanced style and controlling system.
version: 1.0.0
repository: https://github.com/P-YMR/flutter_data_management.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_entity: ^1.0.3
  in_app_database: ^1.2.7
  in_app_query: ^1.0.2
  firebase_database: ^11.0.3
  cloud_firestore: ^5.1.0
  dio: ^5.4.2+1
  connectivity_plus: ^6.0.3
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: