name: data_management
description: Collection of service with advanced style and controlling system.
version: 0.0.4
homepage: https://github.com/P-YMR/flutter_data_management.git

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  flutter_bloc: ^8.1.3
  connectivity_plus: ^4.0.1
  shared_preferences: ^2.1.2
  firebase_database: ^10.2.3
  cloud_firestore: ^4.8.1
  dio: ^5.2.1+1
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: