name: data_management
description: Collection of service with advanced style and controlling system.
version: 2.4.3
repository: https://github.com/Mohiuddin655-PUB/flutter_data_management

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.13.0
  encrypt: ^5.0.3
  flutter_entity: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0