name: data_management_realtime_delegate
description: Collection of service with advanced style and controlling system.
version: 1.0.6
repository: https://github.com/P-YMR/flutter_data_management.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.11.0
  firebase_database: ^11.3.4
  data_management: ^2.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
